# Lumo UI Plugin
# This file is used to store configurations for the Lumo UI Plugin
# Do not delete this file

ThemeName=LucidTheme
ComponentsDir=designsystem/src/main/java/dev/staticvar/designsystem/
PackageName=dev.staticvar.designsystem
# Uncomment this line if you are using Kotlin Multiplatform
# KotlinMultiplatform=false 