pid /tmp/nginx.pid;
events { worker_connections 128; }
http {
 include /etc/nginx/mime.types;
 default_type application/octet-stream;
 access_log off;
 error_log /dev/stderr warn;
 server_tokens off;
 client_body_temp_path /tmp/client_temp;
 proxy_temp_path /tmp/proxy_temp;
 fastcgi_temp_path /tmp/fastcgi_temp;
 uwsgi_temp_path /tmp/uwsgi_temp;
 scgi_temp_path /tmp/scgi_temp;
 server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;
  location = /.well-known/apple-app-site-association {
   default_type application/json;
   try_files $uri =404;
  }
  location = /android { return 302 https://play.google.com/store/apps/details?id=dev.staticvar.vlr; }
  location = /source { return 302 https://github.com/static-var/vlr-gg; }
  location = /issues { return 302 https://github.com/static-var/vlr-gg/issues; }
  location = /backend-source { return 302 https://github.com/akhilnarang/vlrgg-scraper; }
  location ~ ^/(match|event|team|player)/[0-9]+/?$ {
   rewrite ^ /open/index.html last;
  }
  location / { try_files $uri $uri/ =404; }
  location = /healthz { access_log off; return 200 'ok\n'; add_header Content-Type text/plain; }
 }
}
