/*
 * Copyright (c) 2022-2026 Shreyansh Lodha
 * SPDX-License-Identifier: MIT
 */
package dev.staticvar.vlr.remotesource.network

import dev.staticvar.vlr.core.network.NetworkMonitor
import dev.staticvar.vlr.core.network.NetworkStatus
import io.ktor.client.HttpClientConfig
import io.ktor.client.plugins.HttpRequestRetry
import io.ktor.client.plugins.HttpTimeout
import io.ktor.client.plugins.HttpRequestTimeoutException
import io.ktor.client.plugins.api.createClientPlugin
import io.ktor.client.network.sockets.ConnectTimeoutException
import io.ktor.client.network.sockets.SocketTimeoutException
import io.ktor.client.plugins.compression.ContentEncoding
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.plugins.defaultRequest
import io.ktor.client.plugins.logging.LogLevel
import io.ktor.client.plugins.logging.Logger
import io.ktor.client.plugins.logging.Logging
import io.ktor.client.request.headers
import io.ktor.client.request.url
import io.ktor.http.HttpHeaders
import io.ktor.http.HttpMethod
import io.ktor.http.encodedPath
import io.ktor.serialization.kotlinx.json.json
import kotlinx.coroutines.CancellationException
import kotlinx.io.IOException
import kotlinx.serialization.json.Json

internal fun HttpClientConfig<*>.configureHttpClient(
  json: Json,
  configuration: NetworkConfiguration,
  acceptLanguageProvider: AcceptLanguageProvider,
  networkMonitor: NetworkMonitor,
) {
  expectSuccess = true

  defaultRequest {
    url {
      host = configuration.host
      protocol = configuration.defaultProtocol
    }
    headers {
      configuration.defaultHeaders.forEach { append(it.key, it.value) }
      if (!contains(HttpHeaders.AcceptLanguage)) {
        acceptLanguageProvider.acceptLanguage()?.let { append(HttpHeaders.AcceptLanguage, it) }
      }
    }
  }

  install(ContentNegotiation) { json(json) }
  install(NetworkTelemetry)

  install(OfflineLiveUpdateGuard) { monitor = networkMonitor }
  install(HttpRequestRetry) {
    maxRetries = 3
    retryIf { request, response ->
      networkMonitor.status.value != NetworkStatus.Offline &&
        isRetryableLiveUpdate(request.method, request.url.encodedPath) &&
        (response.status.value == 408 || response.status.value == 429 || response.status.value in 500..599)
    }
    retryOnExceptionIf { request, cause ->
      networkMonitor.status.value != NetworkStatus.Offline &&
        isRetryableLiveUpdate(request.method, request.url.encodedPath) &&
        isRetryableTransportFailure(cause)
    }
    exponentialDelay(baseDelayMs = 1_000, maxDelayMs = 4_000, randomizationMs = 500)
    modifyRequest { _ ->
      if (networkMonitor.status.value == NetworkStatus.Offline) throw OfflineLiveUpdateException()
    }
  }

  install(HttpTimeout) {
    requestTimeoutMillis = configuration.timeoutMillis
    connectTimeoutMillis = configuration.timeoutMillis
    socketTimeoutMillis = configuration.timeoutMillis
  }

  if (configuration.enableCompression) {
    install(ContentEncoding) { gzip() }
  }

  if (configuration.enableNetworkLogs) {
    install(Logging) {
      logger = object : Logger {
        override fun log(message: String) {
          println("Ktor: $message")
        }
      }
      level = LogLevel.INFO
    }
  }
}

/** Rejects scoped live-update writes immediately when connectivity is known to be absent. */
private val OfflineLiveUpdateGuard = createClientPlugin("OfflineLiveUpdateGuard", ::OfflineLiveUpdateGuardConfig) {
  val monitor = pluginConfig.monitor
  onRequest { request, _ ->
    if (monitor.status.value == NetworkStatus.Offline &&
      isRetryableLiveUpdate(request.method, request.url.encodedPath)
    ) {
      throw OfflineLiveUpdateException()
    }
  }
}

/** Holds the live connectivity snapshot source used by the request guard. */
private class OfflineLiveUpdateGuardConfig {
  lateinit var monitor: NetworkMonitor
}

/** Signals that a scoped write was intentionally not sent while offline. */
private class OfflineLiveUpdateException : IOException("Live update is offline")

/** Limits replay to idempotent token and favorites writes for a client UUID. */
internal fun isRetryableLiveUpdate(method: HttpMethod, encodedPath: String): Boolean {
  val segments = encodedPath.trim('/').split('/')
  if (segments.size != 6 || segments.take(4) != listOf("api", "v1", "live-updates", "clients")) return false
  if (!ClientUuid.matches(segments[4])) return false
  return when (segments[5]) {
    "token" -> method == HttpMethod.Put || method == HttpMethod.Delete
    "favorites" -> method == HttpMethod.Put
    else -> false
  }
}

private val ClientUuid = Regex("[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")

/** Timeout cancellation is generated by Ktor; ordinary caller cancellation is never replayed. */
private fun isRetryableTransportFailure(cause: Throwable): Boolean {
  if (cause is IOException) return true
  if (cause !is CancellationException) return false
  var nested = cause.cause
  while (nested is CancellationException) nested = nested.cause
  return nested is HttpRequestTimeoutException || nested is ConnectTimeoutException || nested is SocketTimeoutException
}
